name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install devscripts
        run: |
          sudo apt update -qq
          sudo apt full-upgrade -y
          sudo DEBIAN_FRONTEND=noninteractive apt -qq -y install devscripts equivs lintian
          mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

     - name: build source package
       env:
         DEBFULLNAME: "Github Actions"
         DEBEMAIL: "jakob.flierl@gmail.com"
         TARGET: ${{ matrix.target }}
       run: |
         git fetch --unshallow
         git fetch --tags
         VERSION="$(git describe --tags | sed -e "s/^v//" -e "s/-/+git/")"
         dch --create \
             --distribution ${TARGET} \
             --package qgcoder \
             --newversion ${VERSION}~${TARGET}1 \
             "Automatic build from Github"
         debuild -S -sa -us -uc -d

      - name: Build and install QGCoder/libqgcodeeditor
        run: |
          git clone --depth 1 https://github.com/QGCoder/libqgcodeeditor
          cd libqgcodeeditor
          mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"
          dpkg-buildpackage -b -rfakeroot -us -uc
          sudo dpkg -i ../libqgcodeeditor*deb
          sudo apt -y -f install

      - name: Build and install QGCoder/qgcoder
        run: |
          dpkg-buildpackage -b -rfakeroot -us -uc
          sudo dpkg -i ../qgcoder*.deb
          sudo apt -y -f install
          ls -alrt

      - name: Run lintian
        run: lintian ../libqgcodeeditor*deb | lintian-info

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-${{ matrix.target }}
          if-no-files-found: error
          path: |
            *.buildinfo
            *.changes
            *.dsc
            *.tar.*
            *.deb
            ~/**/*/*.buildinfo
            ~/**/*/*.changes
            ~/**/*/*.dsc
            ~/**/*/*.tar.*
          ~/**/*/*.deb
